### ISSUE TITLE
Error when searching the word "fuller's"

### ISSUE THREAD

**Issue by miki95** [Rlshep/BJCP2015BeerStyles#16]
When searching the word "fuller's", the next error appears

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.rlshep.bjcp2015beerstyles/io.github.rlshep.bjcp2015beerstyles.SearchResultsActivity}: android.database.sqlite.SQLiteException: near "s": syntax error (code 1): , while compiling: SELECT right FROM SYNONYMS WHERE  language = 'English' AND UPPER(left) = UPPER('fuller's')
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: android.database.sqlite.SQLiteException: near "s": syntax error (code 1): , while compiling: SELECT right FROM SYNONYMS WHERE  language = 'English' AND UPPER(left) = UPPER('fuller's')
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
	at io.github.rlshep.bjcp2015beerstyles.db.BjcpDataHelper.searchSynonyms(BjcpDataHelper.java:211)
	at io.github.rlshep.bjcp2015beerstyles.db.BjcpDataHelper.search(BjcpDataHelper.java:192)
	at io.github.rlshep.bjcp2015beerstyles.SearchResultsActivity.onCreate(SearchResultsActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:6672)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
	... 9 more

************ DEVICE INFORMATION ***********
Brand: motorola
Model: Moto G (4)

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: 5

**Comment by Rlshep** [comment]
Hi @miki95 do you mind testing the change at https://play.google.com/apps/testing/io.github.rlshep.bjcp2015beerstyles ?
